### ISSUE TITLE
Warning coming from SQLAlchemy

### ISSUE THREAD

**Issue by kalbermattenm** [sitn/crdppf_core#152]
This is probably a security issue:

```
[Fri Jun 15 16:27:30.884216 2018] [wsgi:error] [pid 488:tid 3816] d:\\applications\\crdppf\\.build\\venv\\Lib\\site-packages\\sqlalchemy\\sql\\elements.py:4267: SAWarning: Textual SQL expression u"id IN ('62_1505')" should be explicitly declared as text(u"id IN ('62_1505')")
```

**Comment by voisardf** [comment]
basically resolved by https://github.com/sitn/crdppf_core/pull/155
but strange thing is, we lose the property hilighting with this PR! And I have not found out why yet, because the resulting url looks the same for the old and new code... strange, strange

**Comment by voisardf** [comment]
Solved somewhen on the way
