### ISSUE TITLE
Change for Pyramidoereb 1.2.3

### ISSUE THREAD

**Issue by sitj-raphael** [sitn/crdppf_core#160]
CONST_requirements.txt
-Shapely==1.6.2
+Shapely==1.6.4.post1

CONST_versions.txt
-GeoAlchemy2==0.4.2
+geoalchemy2==0.5.0
-SQLAlchemy==1.2.6
+SQLAlchemy==1.2.11
-psycopg2==2.7.4
+psycopg2==2.7.5
-pyramid==1.9.1
+pyramid==1.9.2
-pyyaml==3.12
+pyyaml==3.13
-requests==2.18.4
+requests==2.19.1
-simplejson==3.13.2
+simplejson==3.16.0
-urllib3==1.22
+urllib3==1.23

Thank's

**Comment by voisardf** [comment]
I think we can close that one? :)
