### ISSUE TITLE
Erreur Py3

### ISSUE THREAD

**Issue by sitj-raphael** [sitn/crdppf_core#169]
Hello,
Tu as une erreur avec python3
https://github.com/sitn/crdppf_core/blob/py3/crdppf/util/get_feature_functions.py#L10

Avant c'était
from crdppfportal.table2model_match import table2model_match
Et avec py3
from crdppf.util.table2model_match import table2model_match
Du coup cela bug avec le R76 que l'on a jouter ;-(

Tu peux corriger ?
Merci

**Comment by voisardf** [comment]
should be ok now.
fixed by PR https://github.com/sitn/crdppf_core/pull/171 and PR https://github.com/sitn/crdppf_core/pull/172

**Comment by voisardf** [comment]
Please close the issue once verified.

**Comment by sitj-raphael** [comment]
Tout bon ;-)
Merci
