### ISSUE TITLE
On the py3 branch I get the following error on printing ...

### ISSUE THREAD

**Issue by sbrunner** [sitn/crdppf_core#171]
```
Extra Properties: 

 * title

All allowed properties are: 

 * officialtitle
 * remoteurl
```

**Comment by voisardf** [comment]
that might be related to this one:
https://github.com/sitn/crdppf_core/blob/py3/print/print-apps/crdppf/config.yaml#L128

strangely, we didn't get this error before... What happens if you comment the title tag in the conf.yaml?

**Comment by sbrunner** [comment]
It get worth, but if I add a title here:
https://github.com/sitn/crdppf_core/blob/py3/print/print-apps/crdppf/config.yaml#L131
https://github.com/sitn/crdppf_core/blob/py3/print/print-apps/crdppf/config.yaml#L122
This error is fixed, but I will get a new one of the same style, than I suspect a more general error, what do you think?

**Comment by voisardf** [comment]
Closing as commented in the PR https://github.com/sitn/crdppf_core/pull/173
