### ISSUE TITLE
Wrong indent

### ISSUE THREAD

**Issue by kalbermattenm** [sitn/crdppf_core#46]
https://github.com/sitn/crdppf_core/blob/master/crdppf/static/js/Crdppf/main.js#L413

**Comment by voisardf** [comment]
@monodo : I let you do it 'en passant' https://github.com/monodo/crdppf_core/blob/master/crdppf/static/js/Crdppf/main.js#L413

**Comment by voisardf** [comment]
Done by PR https://github.com/sitn/crdppf_core/pull/68
