### ISSUE TITLE
Legend panel disappears

### ISSUE THREAD

**Issue by kalbermattenm** [sitn/crdppf_core#57]
Sometime the legend panel overrides the featuretree panel.

This must have something to do with missing js variable declaration...

**Comment by monodo** [comment]
This issue should now be solved.

The featureTree's panel is now created during UI initialization. The [featureTree](https://github.com/monodo/crdppf_core/blob/client_refactor/crdppf/static/js/Crdppf/featurePanel.js#L15) now belongs to the FeaturePanel object that is instantiated [here](https://github.com/monodo/crdppf_core/blob/client_refactor/crdppf/static/js/Crdppf/main.js#L129)

Does that looks ok to you, @kalbermattenm ?

**Comment by kalbermattenm** [comment]
I'll leave this to @voisardf, as he originally created this issue (thus he might be the best person to reproduce it...)

**Comment by voisardf** [comment]
Problem is, occurences seem to be random and there is no recipe to reproduce it. Jura has discoverd the issue, I also have seen it. But I hope it's solved by your refactoring. We'll see.
