### ISSUE TITLE
IE11 - Changing theme crashes - timeout

### ISSUE THREAD

**Issue by kalbermattenm** [sitn/crdppf_core#60]

**Comment by monodo** [comment]
@kalbermattenm please provide detailed description (activated layers, active control, etc...).

**Comment by kalbermattenm** [comment]
To reproduce, open IE9 or IE11... (go and get yourself a coffee...):
* Select theme "Aménagement du territoire"
* Then select theme "Routes nationales"

The theme loader (in the theme panel) does not get away anymore, maybe because this theme is currently empty, maybe because.... I don't know...

**Comment by voisardf** [comment]
https://github.com/sitn/crdppf_core/pull/68
