### ISSUE TITLE
Reordering/hiding of attributes

### ISSUE THREAD

**Issue by kalbermattenm** [sitn/crdppf_core#62]
- [x] Reorder attribute display for restriction (on the client side -> reorder store given by json)
- [x] Allow hiding of attributes (check if that can be done directly in the MapFile)

**Comment by monodo** [comment]
Should be done in Mapserver

**Comment by kalbermattenm** [comment]
Hmmmm... Yes and no... It quite depends... Here we return json data, which means that this has nothing to do with mapserver, but is rather an answer of the mapfish protocol (or some kind of home made json).

The issue with json, is that it doesn't contain any information about attribute order, even if you produce it (on the server side) with the right order, the client side might reorder it in a complete random way...

We should really look at this carefully.

**Comment by voisardf** [comment]
Done by PR https://github.com/sitn/crdppf_core/pull/74
