### ISSUE TITLE
Define PIL/pillow version

### ISSUE THREAD

**Issue by voisardf** [sitn/crdppf_core#89]
PIL 1.1.7 does not load correctly on linux and pillow 2.1.0 throws also an error. Pillow 2.8.x works on linux but may has issues with windows/GeoMapfish. - We have to define what version fits both OS and fix it in the versions.cfg

**Comment by kalbermattenm** [comment]
Yes, will do

For my own (not so good) memory: create a wheel rep, create a new buildout section (see in sitn_c2cgeoportal, branch 1.6), activate it only if Windows (for linux do not use it...)

**Comment by voisardf** [comment]
Version 2.8.1 does the trick
